services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    env_file: backend/.env
    depends_on:
      - redis-stack
      - postgres
  frontend:
    build: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  redis-stack:
    image: redis/redis-stack
    container_name: redis1
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: DK10
      POSTGRES_PASSWORD: Test
      POSTGRES_DB: movie_review
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:

