services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: psql
    environment:
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: Test
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
