services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis1
    volumes:
      - "./data:/data"
#    environment:
#      - REDIS_ARGS=--user virtue on +@all ~* >moneypal
    ports:
      - "6379:6379"
      - "8001:8001"
